name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Install dependencies
      run: go mod download
    
    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -v ./...
    
    - name: Build macOS app
      run: |
        chmod +x build.sh
        ./build.sh
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Kernel-Task-Monitor-macOS
        path: "Kernel Task Monitor.app"